# Generated by Django 4.1.2 on 2023-06-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='my_app/static/img/photos/', verbose_name='Photo'),
        ),
    ]
